### ISSUE TITLE
References in models support

### ISSUE THREAD

**Issue by zuf** [andyw8/cucumber_scaffold#1]
Hello what about references in models?
I take this error: 
    feature_generator.rb:164:in `default_value': Cannot create default value for attribute type 'references' (RuntimeError)

**Comment by andyw8** [comment]
Sorry, only string, text and integer types are supported in this first release, but you can add any other fields by hand after running the generator.

**Comment by zuf** [comment]
I made a small hacks for additional attributes and make pull request.

**Comment by andyw8** [comment]
Thanks! I will apply that shortly.

**Comment by andyw8** [comment]
Done
